version: 0.2
phases:
#   install:
#     runtime-versions:
#       dotnet: 3.1
  build:
    commands:
      - apt update
      - apt install snapd
      - snap install yq
      - export VERSION=$(yq e '.spec.containers[0].env[0].value' test.yaml)
      - echo $VERSION


