version: 0.2
phases:
#   install:
#     runtime-versions:
#       dotnet: 3.1
  build:
    commands:
      - apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CC86BB64
      - add-apt-repository ppa:rmescandon/yq
      - apt update
      - apt install yq -y
      - yq --version
      - yq r test.yaml 'spec.containers[0].env[0].value'
      - yq r test.yaml 'spec.containers[0].env[0].value' >> 1.txt
      - VERSION=`yq r test.yaml 'spec.containers[0].env[0].value'`
      - echo $VERSION
      - ls
      - cat 1.txt


