version: 0.2
env:
  variables:
    git_url: "git@github.com:Thrinadh-Kumpatla/deploy-repo.git"
  parameter-store:
    ssh_key: /codebuild/build-deploy/ssh-key
phases:
  install:
    commands:
      - wget https://github.com/mikefarah/yq/releases/download/v4.9.6/yq_linux_amd64 -O /usr/bin/yq
      - chmod +x /usr/bin/yq
      - apt update
      - apt install -y git
  build:
    commands:
      - mkdir -p ~/.ssh
      - echo "$ssh_key" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - eval “$(ssh-agent -s)"
      - VERSION=`yq e '.spec.containers[0].env[0].version' test.yaml`
      - yes | git clone git@github.com:Thrinadh-Kumpatla/deploy-repo.git
      - git remote -v
      - cd deploy-repo
      - git remote -v
      - git config --global user.email "kthrinadh8898@gmail.com"
      - git config --global user.name "Thrinadh-Kumpatla"
      - git remote add origin https://github.com/Thrinadh-Kumpatla/deploy-repo.git
      - git checkout -b "version-change-branch"
      - yq eval '.spec.containers[0].env[0].version = $VERSION' deploy.yaml >> deploy.yaml
      - cat deploy.yaml
      - git add .
      - git commit -m "changing version"
      - git push -u origin version-change-branch
