version: 0.2
env:
  parameter-store:
    GITHUB_TOKEN: "build-deploy-pkey"
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - wget https://github.com/mikefarah/yq/releases/download/v4.9.6/yq_linux_amd64 -O /usr/bin/yq
      - chmod +x /usr/bin/yq
      - apt update
      - apt install -y git 
      - apt update
      - apt install -y hub
  build:
    commands:
      - export VERSION=3.3
      - git clone https://$GITHUB_TOKEN@github.com/Thrinadh-Kumpatla/deploy-repo.git
      - cd deploy-repo
      - git config --global user.email "kthrinadh8898@gmail.com"
      - git config --global user.name "Thrinadh-Kumpatla"
      - git checkout -b version-change-\"$VERSION\"
      - yq eval -i ".spec.containers[0].env[0].version=\"$VERSION\"" deploy.yaml
      - git add .
      - git commit -m "changing version"
      - git push -u origin version-change-\"$VERSION\"
      - hub pull-request -m "PR for rudder-transformer version change-\"$VERSION\" " 

