version: 0.2
phases:
  install:
    commands:
      - wget https://github.com/mikefarah/yq/releases/download/v4.9.6/yq_linux_amd64 -O /usr/bin/yq
      - chmod +x /usr/bin/yq
      - apt update
      - apt install -y git
  build:
    commands:
      - lsb_release -a
      - yq --version
      - ls
      - yq eval '.spec.containers[0].env[0].version' test.yaml
      - git --version
      - VERSION=`yq e '.spec.containers[0].env[0].version' test.yaml`
      - echo $VERSION
      - cat test.yaml
      - git config --global user.email "kthrinadh8898@gmail.com"
      - git config --global user.name "Thrinadh-Kumpatla"
      - git remote get-url origin
      - git remote -v
      - git clone https://github.com/Thrinadh-Kumpatla/deploy-repo.git
      - git remote remove origin
      - git remote set-url origin https://github.com/Thrinadh-Kumpatla/deploy-repo.git
      - git remote get-url origin
      - cd deploy-repo
      - git checkout -b "version-change-branch"
      - yq eval '.spec.containers[0].env[0].version = $VERSION' deploy.yaml >> deploy.yaml
      - cat deploy.yaml
      - git add .
      - git commit -m "changing version"
      - git push -u origin version-change-branch
