version: 0.2
env:
  parameter-store:
    ssh_key: "build-deploy-github-key"
    GITHUB_TOKEN: "build-deploy-pkey"
phases:
  install:
    commands:
      - wget https://github.com/mikefarah/yq/releases/download/v4.9.6/yq_linux_amd64 -O /usr/bin/yq
      - chmod +x /usr/bin/yq
      - apt update
      - apt install -y git 
      - apt update
      - apt install -y hub
  build:
    commands:
#       - export GITHUB_TOKEN="$GITHUB_TOKEN"
#       - mkdir -p ~/.ssh
#       - echo "$ssh_key"
#       - echo "$ssh_key" > ~/.ssh/id_rsa
#       - chmod 600 ~/.ssh/id_rsa
#       - eval "$(ssh-agent -s)"
      - VERSION=`yq e '.spec.containers[0].env[0].version' test.yaml`
      - yes | git clone https://$GITHUB_TOKEN@github.com/rudderlabs/rudder-devops.git
      - git remote -v
      - hub --version
      - cd rudder-devops/helm-charts/shared-services/per-az
      - git remote -v
#       - git config --global user.email "kthrinadh8898@gmail.com"
#       - git config --global user.name "Thrinadh-Kumpatla"
      - git checkout -b version-change-\"$VERSION\"
      - yq eval ".rudder-transformer.image.tag=\"$VERSION\"" values.enterprise.yaml >> values.enterprise1.yaml
      - rm -rf values.enterprise.yaml
      - mv values.enterprise1.yaml values.enterprise.yaml
      - cat values.enterprise.yaml
#       - git add .
#       - git commit -m "changing version"
#       - git push -u origin version-change-\"$VERSION\"
#       - hub pull-request -m "PR for rudder-transformer version change-\"$VERSION\" " -a "Thrinadh-Kumpatla"
