version: 0.2
env:
  parameter-store:
    GITHUB_TOKEN: "build-deploy-pkey"
    MAIL: "mail-id"
    USER_NAME: "user-name"
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - wget https://github.com/mikefarah/yq/releases/download/v4.9.6/yq_linux_amd64 -O /usr/bin/yq
      - chmod +x /usr/bin/yq
#       - yum install -y hub
      - apt-get update
      - pkg install hub
  build:
    commands:
      - export VERSION=3.39
      - git clone https://$GITHUB_TOKEN@github.com/Thrinadh-Kumpatla/deploy-repo.git
      - cd deploy-repo
      - git config --global user.email \"$MAIL\"
      - git config --global user.name \"$USER_NAME\"
      - git checkout -b version-change-\"$VERSION\"
      - yq eval -i ".spec.containers[0].env[0].version=\"$VERSION\"" deploy.yaml
      - git add deploy.yaml
      - git commit -m "changing version for transformer"
      - git push -u origin version-change-\"$VERSION\"
      - hub pull-request -m "PR for rudder-transformer version change-\"$VERSION\" " 

